# Generated by Django 5.0.7 on 2024-10-17 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=25, unique=True)),
                ('assunto', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('aguardando_analise', 'Aguardando Análise'), ('em_analise', 'Em Análise'), ('com_pendencia', 'Com Pendência'), ('concluida', 'Concluída'), ('encaminhada', 'Encaminhada'), ('cancelada_sistema', 'Cancelada pelo Sistema'), ('cancelada_usuario', 'Cancelada pelo Usuário')], default='aguardando_analise', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('requerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerente_solicitacoes', to=settings.AUTH_USER_MODEL)),
                ('ultimo_analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisou_solicitacoes', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
